travis:
  secure:
    BINSTAR_TOKEN: M2QMa6KWR2QUyW85bS4VKHu+LbjE3gOSBMk/rxjAbnbgdlK37ElUyNZkNbxZ9rnkg2tJEgZiwKJP6r+wQ1sCuXGgPMHkW4ITJ4NrBy+WithEjgS5qCg9BzzXbSpyywsPl4Neu/c1IMvnfZV9XA84e2GO6wMKOksPGAh+0mtti20xT0XqzAKmBeUW5ICt/hK8JDADMtpIVLkXFS7fzL9tcqis7BqJE6R/ucFSMKMCQN/Qy917iSHLB1C5OLsuysLZimoFmQzrBMtr32ZLWJpnJFBjR39164ovK86IvgZUh/YQXOxeacw7yKKuPHYv0ckJALCSISEEThGwwBF/LhlwTrXJB+z5R7KkwPKsDFaEm4VseVDIiBViWKAygc9EDVD1Yhb9mVabzFhn84vT8TEHEjbNwrqtXURctXlMJ4hwUGcvqoQ8WP6+AXJ8Ljr+F59BgXybm7/+IiOdepcBFZGa7SOZcCLVqsbkHd2oppfr6HzPTLK+jHZVLTfJasLh8JCwpwzEBevlOjRejfPFQN5dKBal0zmf1p8o6qhFwMuxeLazSIoBAKs3WUkf3kWnHoR2nh5C5pZ+CfCpRxfVVObocOeqGP1HA/W5FVM0r2f3GPbBPhC8P9gDUnp+0krJtRW1zMEYlbyjZRelpM8QIFldyr+JT97DW+meFzegFikCHfc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
